### ISSUE TITLE
Logo center renders with jagged edges on some browsers/devices

### ISSUE THREAD

**Issue by Methodician** [Methodician/CoSourcery#111]
In Chrome (Mac) logo center gets jagged edges. In Chrome (Android) it doesn't. Weird...

Example: 
![screen shot 2018-11-10 at 8 04 21 am](https://user-images.githubusercontent.com/4460470/48449819-b1260f80-e758-11e8-9bfe-963764abb681.png)

**Comment by m-chu** [comment]
Fixed with new logo.svg file in 'logo-update' branch.
